### ISSUE TITLE
Warning message: In readLines

### ISSUE THREAD

**Issue by millstei** [MingzhiYe16/CITpkg#1]
When installing this package, I got a warning:

Warning message:
In readLines(old_path) :
  incomplete final line found on '/Users/joshuamillstein/.R/Makevars'

I guess we need to replace with a relative path or something.

Josh

**Comment by MingzhiYe16** [comment]
I will fix it.

millstei ***@***.***>于2024年10月10日 周四下午4:26写道：

**Comment by MingzhiYe16** [comment]
The problem is that R tried to use Makevars files in your system rather than in the package. So you should remove /Users/joshuamillstein/.R.  This path is we created last time when I weren't familiar with Makevars.
