### ISSUE TITLE
combine cit functions

### ISSUE THREAD

**Issue by millstei** [MingzhiYe16/CITpkg#5]
Combine cit.bp, cit.bp.m.v1, cit.bp.m.v2, cit.bp.v1 and cit.bp.v2 into one function called cit.bp. We already have an argument for v1 vs v2, which is robust=TRUE, so we just need to determine whether G is one or more columns. This can be done simply by determining whether G is a vector or matrix (or dataframe), and if it's a matrix, counting the columns. 

Similarly, combine cit.cp, cit.cp.m.v1, cit.cp.m.v2, cit.cp.v1 and cit.cp.v2 into one function called cit.cp. We already have an argument for v1 vs v2, which is robust=TRUE, so we just need to determine whether G is one or more columns. This can be done simply by determining whether G is a vector or matrix (or dataframe), and if it's a matrix, counting the columns.

**Comment by MingzhiYe16** [comment]
I have already combined and the integrated cit.cp and cit.bp are available.

**Comment by MingzhiYe16** [comment]
it is fixed
