### ISSUE TITLE
misc argument definitions

### ISSUE THREAD

**Issue by millstei** [MingzhiYe16/CITpkg#8]
Changes to some argument definitions.

L    Numeric or integer vector or nxp design matrix or dataframe representing the instrumental variable(s).
G    Numeric or integer vector, matrix, or dataframe representing the candidate causal mediator(s).

For cit.cp
T    Numeric or integer vector, matrix, or dataframe representing the trait or outcome.

For cit.bp
T    Binary integer vector, matrix, or dataframe representing the trait or outcome.

rseed    Random seed for reproducible results. The default (NULL) is to use a clock seed.

robust    The robust version (the default) is a modification that precludes a positive test result (small p-value) for both the causal and reverse causal scenarios.

**Comment by MingzhiYe16** [comment]
It's fixed
